version: '2'
services:
  db:
    image: mdillon/postgis
    volumes:
      - postgres-durable-volume:/var/lib/postgresql/data
  default: &default
    build: .
    environment:
      DOCKER: 'true'
    volumes:
      - .:/app
    depends_on:
      - db
  web:
    <<: *default
    ports:
      - "4000:4000"
    command: mix phx.server
  setup:
    <<: *default
    command: ./setup
  test:
    <<: *default
    command: mix test

volumes:
  postgres-durable-volume:
